language: python
python:
  - "3.6"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda create --yes -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv
  - pip install --upgrade pip
  - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
  - sudo dpkg -i ./nrn-7.7.x86_64-linux.deb
  - export PATH=$PATH:/usr/local/nrn/x86_64/bin
  - export PYTHONPATH=$PYTHONPATH:/usr/local/nrn/lib/python/
  - pip install -r requirements.txt
install:
  - pip install .
script:
  - compilechannels default
  - pytest
